# Generated by Django 5.2.1 on 2025-05-08 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('color', models.CharField(choices=[(None, 'پیش\u200cفرض'), ('red', 'قرمز'), ('green', 'سبز'), ('yellow', 'زرد'), ('blue', 'آبی'), ('magenta', 'سرخابی')], default='پیش\u200cفرض', verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'فهرست',
                'verbose_name_plural': 'فهرست\u200cها',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['title'], name='list_list_title_0eb4aa_idx'), models.Index(fields=['color'], name='list_list_color_3ad2da_idx')],
            },
        ),
    ]
