# Generated by Django 5.2.1 on 2025-05-08 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('completion_status', models.BooleanField(default=False, verbose_name='انجام شده؟')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'خرده\u200cوظیفه',
                'verbose_name_plural': 'خرده\u200cوظیفه\u200cها',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['title'], name='subtask_sub_title_608dad_idx'), models.Index(fields=['completion_status'], name='subtask_sub_complet_06af55_idx')],
            },
        ),
    ]
