# Generated by Django 5.2.1 on 2025-05-08 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('detail', models.TextField(default=None, max_length=512, verbose_name='جزئیات')),
                ('perority', models.CharField(choices=[('very high', 'بسیار بالا'), ('high', 'بالا'), ('moderate', 'متوسط'), ('low', 'کم'), ('very low', 'بسیار کم')], default='moderate', verbose_name='اولویت')),
                ('completion_status', models.BooleanField(default=False, verbose_name='انجام شده؟')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.list', verbose_name='فهرست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظیفه\u200cها',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['title'], name='task_task_title_f107aa_idx'), models.Index(fields=['completion_status'], name='task_task_complet_919d25_idx')],
            },
        ),
    ]
