# Generated by Django 5.2.1 on 2025-05-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-perority'], 'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظیفه\u200cها'},
        ),
    ]
