# Generated by Django 5.2.1 on 2025-05-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super admin', 'ابرمدیر'), ('admin', 'مدیر'), ('user', 'کاربر')], default='user', max_length=20, verbose_name='نقش'),
        ),
    ]
